export const termsAndConditions = {
  header: "Terms & Conditions",

  description: [
    {
      text: `This page defines the Terms & Conditions and sets forth a legal agreement between you and the OptiFii. If you do not agree and accept the conditions of this age, you are advised not to use the website. By accepting the terms, you agree to review this page periodically and are bound to the Terms updated regularly by the OptiFii.`,
    },
    {
      text: `These Terms are an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder as applicable. The Terms are (i) published in accordance with the provisions of Rule 3(1)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 and (ii) generated by a computer system and does not require any physical,electronic, or digital signatures.`,
    },
    {
      text: `By registering on, accessing, browsing, or using the OptiFii website site for any general purpose or for the specific purpose of availing any Service, you agree, automatically and immediately to be bound by this Agreement as well as by any the service specific terms and conditions applicable to each Service, whether you are a visitor or a registered user of OptiFii website and affiliate applications and services.`,
    },
  ],
  data: [
    {
      title: "DEFINITIONS:",

      desc: [
        {
          text: `Unless indicated otherwise, the capitalized terms have the meanings given below:`,
        },
        {
          text: `The term "service" refers to any services offered by OptiFii.`,
          boldtext: [`"service"`],
        },
        {
          text: `The term "user" refers to any visitor, registered customer taking a specific service, an employee registered by its employer company, or an employer registering its employees for various services offered by OptiFii.`,
          boldtext: [`"user"`],
        },
        {
          text: `"Full KYC Wallet" is the Wallet issued to you after completing your full KYC according to the relevant RBI Regulations.`,
          boldtext: [`"Full KYC Wallet"`],
        },
        {
          text: `"Minimum KYC Wallet" is the Wallet issued to you by OptiFii after you provide us 'minimum details' about yourself, these are: your name, mobile number verified with One Time Pin (“OTP”) and the unique identification number given on any of your 'officially valid documents' ("OVD") (or in the limited case of Minimum KYC Wallet, in place of OVD, you may provide the unique identity/identification number of any "mandatory document" as defined in RBI Regulations). The types of OVD we accept are given on the Platform and are in line with Applicable Law. The features of different types of Wallets within this category are described in greater detail in clause 6 of these Terms. `,
          boldtext: [`"Minimum KYC Wallet"`],
        },
        {
          text: `"Preson-to-Bank Transfer" is a facility allowing you to transfer fund from your wallet to your bank account.`,
          boldtext: [`"Preson-to-Bank Transfer"`],
        },
        {
          text: `"Person-to-Merchant Transfer" is a facility allowing you to transfer fund from your wallet to any merchant (who accepts payments from the Wallet for purchase of its goods and services)`,
          boldtext: [`"Person-to-Merchant Transfer"`],
        },
        {
          text: `"Person-to-Person Transfer" is a facility allowing you to transfer funds from your Wallet toany other individual's prepaid payment instrument or bank account (as permitted from time to time).`,
          boldtext: [`"Person-to-Person Transfer"`],
        },
        {
          text: `"PPI Master Directions" is the Master Direction issued by RBI on the 'Prepaid Payment Instruments' on 27 August 2021, as amended from time to time.`,
          boldtext: [`"PPI Master Directions"`],
        },
        {
          text: `"RBI Regulations" are the rules, regulations, guidelines, directions, circulars, notifications or instructions issued and updated by the RBI from time to time.`,
          boldtext: [`"RBI Regulations"`],
        },
        {
          text: `"RBI" is the Reserve Bank of India.`,
          boldtext: [`"RBI"`],
        },
        {
          text: `"Transaction" means a purchase, sale, gift, transfer, delivery, or the arrangement thereof and includes the deposit, withdrawal, exchange or transfer of funds greater than INR 0 (Indian Rupee Zero), by electronic, physical or non-physical means. It is clarified however, that Transaction shall not include any unsuccessful, failed, cancelled, recalled, or interrupted Transaction, which terms shall include but not be limited to Transactions for which a refund/chargeback request is raised and processed. To clarify, a Transaction shall be deemed to be a successful Transaction in the event that such Transaction results in the debiting orcrediting of an amount greater than INR 0 (Indian Rupee Zero) successfully. In the event that a successful Transaction undergoes cancellation, recall, interruption, refund, chargeback, or any such instances of a similar nature, then such Transaction shall immediately upon the raising of such instance, be deemed to be an unsuccessful Transaction.`,
          boldtext: [`"Transaction"`],
        },
        {
          text: `"User" means a user of the Platform, whether below or above the age of 18 (eighteen) years.`,
          boldtext: [`"User"`],
        },
        {
          text: `"Wallet Account" is the account associated with the Wallet issued to you by OptiFii. `,
          boldtext: [`"Wallet Account"`],
        },
        {
          text: `"KYC" stands for 'Know Your Customer' and is a process prescribed under Applicable Law. OptiFii will collect and authenticate your personal identification details to undertake KYC according to Applicable Law and RBI Regulations, before it issues you a Wallet (wherever needed) and offers you related Services.`,
          boldtext: [`"KYC"`],
        },
        {
          text: `The term "OptiFii" is a brand name, which belongs and refers to "GiftrytDigital Ventures Private Limited" (also termed as Company, We, Us) including OptiFii employees, either on contract,internship or full time employment, as a legal entity.\n"OptiFii" shall mean GiftrytDigital Ventures Private Limited, a company incorporated in accordance with the provisions of the (Indian) Companies Act, 2013;`,
          boldtext: [`"OptiFii"`, `"GiftrytDigital Ventures Private Limited"`],
        },
        {
          text: `The term "agreement" refers to the legal binding between the user and OptiFii, after the former's acceptance of the terms and conditions of this page.`,
          boldtext: [`"agreement"`],
        },
        {
          text: `The term "website" refers to https://www.optifii.com/ and https://www.optifii.com/giftcards`,
          boldtext: [`"website"`],

          links: [
            {
              name: "https://www.optifii.com",
              url: "/",
            },
            {
              name: "https://www.optifii.com/giftcards__",
              url: "/giftcards",
            },
          ],
        },
      ],
    },
    {
      title: `Eligibility`,
      desc: [
        {
          text: `The service is available only for users above the age of 18 years. Minor users (under the lawful age of 18 years) are advised to not use the OptiFii website. If an individual under the age of 18 years may access and use the site, they shall do so only with the involvement and guidance of their parents and or legal guardians. In all such instances their parents and or legal guardians will be held responsible for all the terms of this agreement.`,
        },
      ],
    },
    {
      title: `Your Rights`,
      desc: [
        {
          text: `Subject to Your compliance with these Terms and solely during the Subscription Term, you shall have the limited, non-exclusive, revocable, royalty-free, non-transferable, right to (i) access and use the Platform and Services for your internal business purposes in accordance with the pricing plan as specifically stated in the relevant Order Form; (ii) download, install and use mobile/desktop applications and plug- ins to access and use the Platform and Services.`,
        },
      ],
    },
    {
      title: `Your Responsibilities`,
      desc: [
        {
          text: `Your Account: As part of the registration process, You will identify an administrative user name and password for Your Account.\nAcceptable Use: You agree not to (a) license, sublicense, sell, resell, rent, lease, transfer, assign, distribute, timeshare disassemble, reverse engineer, decompile or make the Platform available to any third party, other than Users in furtherance of Your internal business purposes as expressly permitted by these Terms; (b) modify, adapt, or hack the Platform or otherwise attempt to gain or gain unauthorized access to the Platform or related systems or networks; (c) duplicate, mirror, republish, download, the whole or any part of the Platform (d) access the Platform for purposes of benchmarking, creating derivative works based on, or developing or operating products or services in competition with the Platform (e) use the Platform to store or transmit Sensitive Personal Information; (f) use the Platform to store or transmit Customer Data in violation of applicable laws and regulations, including but not limited to violation of any person's privacy rights, export control laws/regulations; (g) access it for purposes of creating derivative works based on, or developing or operating products or services for third-parties in competition with the Platform and/or Services; (f) use the Platform to store or transmit any content that infringes upon any person's intellectual property rights or is unlawful, racist, hateful, abusive, libelous, obscene, or discriminatory; (h) use the Platform to knowingly post, transmit, upload, link to, send or store any viruses, malware, trojan horses, time bombs, or any other similar harmful software; (i) “crawl,” “scrape,” or “spider” any page, data, or portion of or relating to the Platform(through use of manual or automated means) (j) use the Platform for the purposes of cookie tracking, ad exchanges, ad networks, data brokerages, or sending electronic communications (including e-mail) in violation of applicable law; (k) use the Platform to transmit junk, spam, phishing, spoofing, pyramid schemes or other forms of duplicative or unsolicited messages;`,
        },
        {
          text: `2.3. If We inform You that a specified activity or purpose is prohibited with respect to the Platform and/or Services, You will ensure that You immediately cease access to and use of the Platform and Services for such prohibited activity or purpose.`,
        },
        {
          text: `2.4. You shall be responsible for obtaining any approvals, establishing notices or policies for and ensuring compliance with all applicable laws and regulations relating to the collection and transmission of Personal Data of individuals who are Users and/or End Users.`,
        },
        {
          text: `2.5. In order for OptiFii to provide agreed Services via its Platform, on as needed basis, Customer shall work closely with OptiFii to provide reasonable assistance as necessary and more specifically, the Customer shall be willing to share necessary permissions for needed integrations, give access to applicable data collection sources on need basis and share data in the form of CSV upload should any other form of data collection and access is deemed unviable`,
        },
        {
          text: `2.6. Third Party/Supplier Interactions:\nSupplier Interactions: When using the Platform, You may enter into correspondence with and purchase goods and/or services from suppliers. Any such activities and associated terms are solely between You and the applicable third-party supplier and We shall have no obligation or responsibility for such correspondence or purchase between You and such third-party supplier.`,
        },
      ],
    },
    {
      title: "Service",
      desc: [
        {
          text: `OptiFii provides services that are into expense management, employee tax benefits and reward programs. The offered products are tech based solutions enabling employers to manage the expense solutions for their employees.`,
        },
      ],
      childs: [
        {
          type: "list",
          name: "Terms of service :",
          listAnnotation: "number",
          data: [
            {
              name: `You hereby declare that all the services that you avail from OptiFii are our own decisions taken after careful consideration.`,
            },
            {
              name: `You hereby declare that all the information you provide during registration for availing a service are true to your knowledge, any discrepancy arising due to the information furnished by you will be your sole responsibility. Company shall not be held liable in any form.`,
            },
            {
              name: `You further declare that you shall notify in writing any change occurring in your (employer) and your employee's personal details.`,
            },
            {
              name: `You authorize OptiFii to share any promotional information over email and texts.`,
            },
            {
              name: `You declare that any transaction happening between user and OptiFii over the website, with respect to the products offered on the website, shall be the final binding on you and your assigns`,
            },
            {
              name: `OptiFii reserves the right to make changes on any or all the services offered on the website`,
            },
            {
              name: `You declare that any changes made by OptiFii on the website with rest to the services shall become binding on the user`,
            },
            {
              name: `Any enhancements, new features or updates ("Updates") to the Platform are also subject to these Terms and We reserve the right to deploy Updates at any time.`,
            },
            {
              name: `The Platform may temporarily be unavailable due to scheduled downtime for upgrades and maintenance in which case We shall use commercially reasonable endeavours to notify You in advance.`,
            },
            {
              name: `We will use commercially reasonable efforts to provide technical support services in accordance with the following terms:`,
              listAnnotation: "roman",
              type: "list",
              data: [
                {
                  name: `We will provide technical support as specified in the relevant Order Form, with the exclusion of Customer's holidays ("Support Hours").`,
                },
                {
                  name: `We shall inform You of Your Point of Contact at the time of onboarding. However, We reserve the right to change such personnel and deploy Our resources in a manner We deem appropriate, to ensure effective and timely services to the Customer.`,
                },
                {
                  name: `You shall provide Us with an email address containing Your domain such as 'username@companydomain.com to streamline communications with suppliers.`,
                },
                {
                  name: `We will use commercially reasonable efforts to respond to all helpdesk tickets within one (1-3) business day`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      title: `Your Account`,
      desc: [
        {
          text: `While accessing the website, you declare that you are of legal age. Employers shall choose a specific service amongst the various services listed on the website. An employee shall furnish details on personal nature that includes their names, address, date of birth, PAN card and Aadhar card details. We respect your personal information and shall by all means protect your privacy under the Privacy Policy of OptiFii. However, users shall be responsible to keep your account login and password details secure. Any misuse or loss of information arising due to password and login details discrepancy will be the sole responsibility of the user. User shall notify the company in writing in case of an unauthorized login or breach of security of the personal account.`,
        },
      ],
      childs: [
        {
          name: `Intellectual Property`,
          type: `list`,
          listAnnotation: "number",

          data: [
            {
              name: `You agree that OptiFii owns the sole rights to the code, databases, visual-design and layout of the Service. Except for the limited licenses expressly granted to you under this Agreement, no other rights, licenses, or immunities are granted or will be deemed to be granted to you under this Agreement, either expressly, or by implication, estoppel or otherwise. You may access the site solely as intended through the provided functionality of the Service and as permitted under this Agreement and shall at all times abide by the terms set forth herein.`,
            },
            {
              name: `You cannot resell, duplicate or reproduce any information or service from the website without the prior written consent of OptiFii.`,
            },
            {
              name: `You cannot copy or re use any portion of the visual design, logo, trademark, name, service mark without prior written consent of OptiFii.`,
            },
            {
              name: `You cannot alter, deface, mutilate any information from the website without prior written consent of OptiFii.`,
            },
            {
              name: `You agree not to bypass, circumvent, damage or otherwise interfere with any security or other features of the site designed to control the manner in which the Services are used.`,
            },
            {
              name: `You agree not to gain unauthorized access to the Services, to other users’ accounts, names or personally identifiable information, or to other computers or websites connected or linked to the Services`,
            },
            {
              name: `You agree to not engage in any illegal activity that violates the intellectual property rights of the website.`,
            },
            {
              name: `Download any software or framework, copy and duplicate code or install any software that includes a License Agreement unless you sign the License Agreement terms.`,
            },
          ],
        },
        {
          name: `Accounting`,
          type: `list`,
          listAnnotation: "number",
          data: [
            {
              name: `OptiFii offers services that are brought from the website. The payment can be made via an online transaction only i.e NEFT, RTGS.`,
            },
            {
              name: `User agrees to not provide information about any unlawfully held bank account or payment mode.`,
            },
            {
              name: `User indemnifies the company from any loss occurring due to wrong information or any transaction held via an unlawfully held bank account, debit card, credit card, bank cheque`,
            },
          ],
        },
      ],
    },
    {
      desc: [
        {
          text: `User further declares to provide correct information while making a financial transaction against the availed services`,
        },
      ],
    },
    {
      title: `Service Cancellation`,
      desc: [
        {
          text: `If the user desires to cancel the purchased services, the user shall be subject to the terms and conditions of the purchased service and the terms and conditions of the purchased service shall prevail.`,
        },
      ],
    },
    {
      title: `Limitation of Liability`,
      desc: [
        {
          text: `OptiFii will not be responsible for any business loss (including loss of profits, revenue, contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect or consequential loss that is not reasonably foreseeable to both user and us when you commenced using the website. In case of the violation of the terms and conditions agreement, Paz care reserves the right to take appropriate action, at its discretion, against the violator. This paragraph shall survive termination of this Agreement.`,
        },
      ],
    },
    {
      title: `Authorization`,
      desc: [
        {
          text: `Due to the inherent characteristics of the internet, transactions may experience interruptions, transmission blackouts, delays, or inaccuracies in data transfer. The Company assumes no responsibility for communication facility malfunctions beyond its control that could impact the accuracy or timeliness of messages or transactions.\nAdditionally, email communications over the internet cannot be guaranteed as completely secure. The Company is not liable for any damages incurred if Users send messages to the Company or its affiliates, or if the Company or its affiliates respond to such requests via email. Furthermore, the Company disclaims any responsibility for direct, indirect, special, or consequential damages resulting from the use of this Website.`,
        },
      ],
    },
    {
      title: `Third Party Links`,
      desc: [
        {
          text: `This Website may include hyperlinks to other websites or locations on the internet. These links may direct you to websites operated by third parties not affiliated with or related to the Company. They are provided solely to enhance your user experience and for informational purposes. While we strive to include reputable websites and information sources, please note that when you click a link and leave our Website, you will be subject to the terms of use and privacy policies of the destination website.\nThe inclusion of any third-party products or services on this Website does not imply that the company approves, endorses, recommends, guarantees, or provides advice about these third parties or their offerings.\nThe Company is not responsible for the content of any externally linked website or webpage and does not assume liability for any damages or losses resulting from your use of these links. Accessing such websites is at your own risk, and the Company is not a party to any agreements or contracts entered into between you and the provider of these external sites unless explicitly stated otherwise.\nThe Company reserves the right to object to or disable any external links to or from this Website at its discretion`,
        },
      ],
    },
    {
      title: `Refunds and Cancellation`,
      desc: [
        {
          text: `The User acknowledges and agrees that the services and products offered by the Company are non-refundable and non-cancellable. The Company does not permit user-initiated refunds or cancellations. All transactions are deemed final upon completion.`,
        },
      ],
    },
    {
      title: `Indemnity`,
      desc: [
        {
          text: `User agrees to defend, indemnify and hold OptiFii, its directors, employees, agents, contractors, partners, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including without limitation reasonable attorney's fees and costs, arising out of or in connection with any Third Party Applications, your use of this website, your conduct in connection with this website or with other users of the website , or any violation of this Agreement or of any law or the rights of any third party.\n\nThe standard schedule of charges as applicable on date is provided below`,
        },
      ],
      childs: [
        {
          type: "table",
          data: {
            headers: [
              "Description of charges",
              "Standard fees (Amount) in Rs.",
            ],
            rows: [
              ["Card Replacement Fees ( Expense, Benefit, GPR)", "Rs.199+ GST"],
              [
                "Fuel Transaction Surcharge (Plus GST)",
                "1.18% or Rs.11.8 whichever is higher",
              ],
              ["ATM Cash Withdrawal Fees", "Rs.28 including GST"],
              ["ATM Balance Enquiry Fees", "Rs.20 including GST"],
            ],
          },
        },
      ],
    },
    {
      title: `Legal Dispute and Resolution `,
      desc: [
        {
          text: `Any legal issue/dispute arising out of this Agreement, but not exclusive to the use of the Services(unless otherwise specifically stated) are governed by and in accordance with the laws of India. The courts in Mumbai, Maharashtra shall have exclusive jurisdiction in respect of any matters arising here from. This paragraph shall survive termination of this Agreement.\nGrievance officer\nIn case you have any grievance with respect to the Terms & Conditions, please write to us at support@optifii.com`,
          boldtext: [`"Grievance officer"`],
          links: [
            {
              name: "support@optifii.com",
              url: "mailto:support@optifii.com",
            },
          ],
        },
      ],
    },
  ],
};

export const privacyPolicy = {
  header: "Privacy Policy",
  description: [
    {
      text: `This page defines the Terms & Conditions and sets forth a legal agreement between you and the OptiFii. If you do not agree and accept the conditions of this age, you are advised not to use the website. By accepting the terms, you agree to review this page periodically and are bound to the Terms updated regularly by the OptiFii.`,
    },
    {
      text: `This privacy policy ("Policy") explains the purpose of this Policy, the terms 'Us', 'Our' or 'We' refers to OptiFii with Our registered office at B-705, Kailash Business Park Vikhroli West 400079,Mumbai, Maharashtra India. The term 'You' or 'Your' or 'User' refers to (i) a visitor of Our Website www.optifii.com (the "Website"), or (ii) User or potential User of OptiFii's software, provided on OptiFii's mobile application, the Website or through web-plugins (the "Services"). The term Customer in this Policy refers to the entity entering into an Order Form with OptiFii for the subscription of the Services.`,
      boldtext: [
        `"Policy"`,
        `'Us'`,
        `'Our'`,
        `'We'`,
        `'You'`,
        `'Your'`,
        `'User'`,
        `"Website"`,
        `"Services"`,
      ],
      links: [{ name: "www.optifii.com", url: "/" }],
    },
  ],
  data: [
    {
      title: "1. Definitions",
      desc: [
        {
          text: `1.1. "Controller" means the natural or legal person, public authority, agency, or other body which alone or jointly with others, determines the purposes and means of the processing of User Data.`,
          boldtext: ["Controller"],
        },
        {
          text: `1.2. "End-User" means any information relating to an identified or identifiable natural person; an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person.`,
          boldtext: [`"End-User"`],
        },
        {
          text: `1.3. "Personal Data" means any information relating to an identified or identifiable natural person; an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person.`,
          boldtext: [`"Personal Data"`],
        },
        {
          text: `1.4 "Process" means any operation or set of operations which is performed on User Data or on sets of User Data, whether or not by automated means, such as collection, recording, organisation, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, dissemination or otherwise making available, alignment or combination,restriction, erasure or destruction.`,
          boldtext: [`"Process"`],
        },
        {
          text: `1.5 "Processor" means a natural or legal person, public authority, agency, or other body which Processes User Data on behalf of the Controller.`,
          boldtext: [`"Processor"`],
        },
        {
          text: `1.6 "Service(s)" shall have the meaning ascribed to it in the Terms of Use.`,
          boldtext: [`Service`],
        },
        {
          text: `1.7 "Subscriber" means the natural or legal person that has subscribed to the Service(s) by agreeing to the Terms of Use.`,
          boldtext: [`"Subscriber"`],
        },
        {
          text: `1.8 "Subscriber Data" means any information related to Subscriber other than the Personal Data.`,
          boldtext: [`"Subscriber Data"`],
        },
        {
          text: `1.9 "Terms of Use" means the binding contract between Us and You which governs the access and use of the Service(s) by You available at  https://www.optifii.com/terms-conditions`,
          boldtext: [`"Terms of Use"`],
          links: [
            {
              name: "https://www.optifii.com/terms-conditions",
              url: "/terms-conditions",
            },
          ],
        },
        {
          text: `1.10 "User Data" includes both Personal Data and Subscriber Data.`,
          boldtext: [`"User Data"`],
        },
        {
          text: `1.11 "Website(s)" means the websites that We operate.`,
          boldtext: [`"Website"`],
        },
        {
          text: `1.12 "You" and "Your" means an identified or identifiable natural person whose User Data We process as a Controller.`,
          boldtext: [`"You"`, `"Your"`],
        },
      ],
    },
    {
      desc: [
        {
          text: `Any terms used herein below with starting letter capitalized, but not defined under Clause 1 here,shall be defined and meaning ascribed to it as per the Terms of Use.`,
        },
      ],
    },
    {
      title: "Collection of Personal Information",
      type: "list",
      listAnnotation: "alpha-uppercase",
      childs: [
        {
          type: "list",
          listAnnotation: "alpha-uppercase",
          data: [
            {
              name: "When You access the Website, the Personal Information that We directly collect from You includes:",
              type: "list",
              listAnnotation: "bullet",
              data: [
                {
                  name: `Telephone number`,
                },
                {
                  name: `E-mail address`,
                },
                {
                  name: `Any other Personal Information that You provide Us while accessing Our Website.`,
                },
              ],
            },
            {
              name: `We may also receive Your Personal Information while You access our Website indirectly as follows:`,
              type: "list",
              listAnnotation: "bullet",
              data: [
                {
                  name: `IP address(es)`,
                },
                {
                  name: `Information about Your device`,
                },
                {
                  name: `When You use or view Our Website(s), information is collected via Your browser's cookies as described in clause 2 herein.`,
                },
              ],
            },
            {
              name: `When You use the Services, the Personal Information that We directly collect from You includes KYC details such as Aadhar card, voter ID card, passport number, driving license and such other Personal Information collected from You at the time of availing OptiFii Platform/Services or PPI cards.`,
            },
            {
              name: `We may also receive Your Personal Information while You access our Website indirectly as follows:`,
              type: "list",
              listAnnotation: "bullet",
              data: [
                {
                  name: `When You log in to Our Services using single sign-on services such which will authenticate Your identity, We will collect the Personal Information shared with such a single sign-onservice for the purpose of authentication which includes Your name and email address.`,
                },
                {
                  name: `When You download and/or use the Service(s), We automatically collect information on the type of device You use and the operating system version.`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      title: `Cookies`,
      desc: [
        {
          text: `You can browse Our Website without telling Us Your name, address, or personal details. However, some of our web pages may track certain Personal Information about You based on Your behaviour on Our Website. This information may include the URL that You just came from (whether this URL is related to our Services or not), which URL You next go to (whether this URL is related to Our Services or not), Your browser information, and Your IP address. We may use data collection devices on Our Website and Services such as “Cookies” on certain aspects to help analyse inter alia Our web page flow, measure promotional effectiveness, and promote trust and safety. Cookies refer to small files placed on Your hard drive that assist Us in providing Our Services. We offer certain features that are only available through the use of a "Cookie". You are always free to disable Our cookies at any time by using Your browser options, however if You turn off Cookies You may not be able to use certain features on the Website or the Services, for which, we shall not be responsible.`,
        },
      ],
      childs: [
        {
          type: "list",
          listAnnotation: "number",
          name: `The Cookies We use can be categorized as:`,
          data: [
            {
              name: `Essential Cookies: We set essential Cookies that enable core functionality such as security, network management, and accessibility. You may not opt-out of these Cookies. However, You may disable these by changing Your browser settings, but this may affect how the Website(s) functions.`,
            },

            {
              name: `Analytics, Customization and Advertising Cookies: We set these Cookies to help Us improve Our Website(s) by collecting and reporting information on how You use it. The Cookies collect information in a way that does not directly identify anyone.`,
            },
          ],
        },
        {
          data: `When You visit the Website(s), a Cookie banner will be displayed providing additional information about Cookies and options to opt out of non-essential Cookies or similar tracking technologies as required by applicable laws.\n\n`,
        },
      ],
    },

    {
      title: `Third Party Websites`,
      desc: [
        {
          text: `When You are using Our Website, You may be directed to, or come across links to, other websites that are operated and controlled by third parties that We do not control, and You access these websites at Your own risk. We provide links to third-party websites for your convenience only, any links to third-party websites do not imply an endorsement by Us to that third-party website. Clicking on links to third-party websites may allow such a third party to collect Personal Information about You. We do not control the use of cookies by third parties nor are We responsible for the contents of any third-party website, including the privacy practices employed by any of these third parties. When You leave the Website, We encourage You to read the applicable privacy statements of that third-party websites to determine how they will handle Your Personal Information before submitting any Personal Information to such third parties.`,
        },
      ],
    },

    {
      title: `Use of Personal Information`,

      childs: [
        {
          type: "list",
          name: "A. Users of the Services",
          data: [
            {
              name: `Signing in and authentication:`,
              nameBold: true,
              description: `We may use the Personal Information collected from You through single sign-on services toauthenticate Your identity and will help You sign in into the Services.`,
            },
            {
              name: `Analysis by third-parties:`,
              nameBold: true,
              description: `We may use the Personal Information collected from You to improve Our products and Services, by way of sharing such information with third parties for the purposes of analysis. In the event that We share Your Personal Information with third parties, We require all third parties to respect the security of Your Personal Information and to treat it in accordance with the law, and such third parties will be contractually restricted from using Your Personal Information in any manner other than in helping Us;`,
            },
            {
              name: `Promotional Emails or Messages:`,
              nameBold: true,
              description: `We may periodically send promotional emails or messages about new services, special offers, or other information which We think You may find interesting using the email address and phone numbers which You have provided. You may, at any time, modify Your subscription preferences;`,
            },
            {
              name: `Customer Service:`,
              nameBold: true,
              description: `We may use Your Personal Information to resolve disputes that may arise with the use of Our Services, help promote a safe service to all the Users, measure consumer interest in Our Services, detect and protect Us against error, fraud and other criminal activity.`,
            },
            {
              name: `Troubleshooting:`,
              nameBold: true,
              description: `We may use Your IP address to help diagnose problems with Our server, and to administer the Website.`,
            },
            {
              name: `Carry out Our obligations:`,
              nameBold: true,
              description: `We may collect Your Personal Information to carry out Our obligations arising from any agreements entered into between You, or Your employer, and Us, such as allowing Our employer clients to evaluate Your usage of the Services. We will use the Personal Information We collect directly from You, information about how You use the Service and information about how You connect to the Service for this purpose.`,
            },
            {
              name: "Notification:",
              nameBold: true,
              description: `We may collect Your Personal Information to notify You about changes to the Service and address complaints, comments, and issues You have in relation to Your use of the Service.`,
            },

            {
              name: `Prevent illegal activities:`,
              nameBold: true,
              description: `We may also collect Personal Information from You to prevent, detect and investigate illegal activities, breaches of any agreements entered into between You and Us and threats to the security of the Service. In the event that any Personal Information is compromised as a breach of security, We will promptly notify You in compliance with applicable law. Other than the Personal Information collected under clause 1 and for the purposes set forth above for which OptiFii shall act as the controller, for any other processing of Personal Information collected from a User, OptiFii will only act as a processor and such processing will be governed by the agreement between OptiFii and the Customer. In such cases, the User's data privacy questions and requests should be submitted to the Customer in its capacity as the User's Controller. If the User is an individual who interacts with a Customer using Our Services, the User will be directed to contact Our Customer for assistance with any requests or questions relating to their Personal Information. We are not responsible for the Customer's privacy or security practices which may be different from this notice. Customers to Our Services are solely responsible for establishing policies for and ensuring compliance with all applicable laws and regulations, as well as any and all privacy policies, agreements, or other obligations, relating to the collection of Personal Information in connection with the use of Our Services by Users.`,
            },
          ],
        },

        {
          name: "Where your personal information is stored",
          nameBold: true,
          data: `Your Personal Information which We have collected may be stored and processed in India or any other country in which OptiFii or its subsidiaries, affiliates or service providers maintain facilities. We will ensure that the recipient of Your Personal Information offers an adequate level of protection that is at least similar to that which is provided under applicable data protection laws. We may transfer information that We collect about You, including Personal Information, to affiliated entities, or to other third parties across borders and from Your country or jurisdiction to other countries or jurisdictions around the world. These countries may have data protection laws that are different to the laws of Your country and, in some cases, may not be as protective. If You are a resident of the European Economic Area and when Your Personal Information is processed outside EEA, We will ensure that the recipient of Your Personal Information offers an adequate level of protection, for instance by a) entering into standard contractual clauses for the transfer of Personal Information as approved by the European Commission (Article 46 General Data Privacy Regulation, 2016), b) We will ask You for Your prior consent to such international data transfers; or c) by ensuring that the transfer of Personal Information is to a jurisdiction deemed to have an adequate level of protection by the European Commission.`,
        },
        {
          name: "Disclosure of personal information",
          type: "list",
          data: [
            {
              name: "We may disclose Your Personal Information to third parties:",
              type: "list",
              listAnnotation: "number",
              data: [
                {
                  name: `In the event that We sell or transfer Our business or assets (in part or whole), in which case We may have to disclose Your Personal Information to the buyer or recipient of such business or assets. Such buyer or recipient shall be informed of the obligations of privacy as under this Policy and applicable law and shall be required to maintain the same norms of privacy as stated herein. You will be informed via email and/or a prominent notice on Our Website of any change in ownership or uses of Your Personal Information, as well as any choices You may have regarding Your Personal Information. We will endeavour that the transferee who is the recipient of    substantially similar to the measures under this Policy.`,
                },
                {
                  name: `We share Personal Information with Our third-party service providers that host and maintain the Our Website(s), applications, backup, storage, payment processing, analytics, marketing and promotions and other services in compliance with applicable laws. These third-party service providers may have access to or Process Your Personal Information for the purpose of providing these Services to Us.`,
                },
                {
                  name: `In order to respond to a subpoena, summons, court order or other legal duty or obligation,requests or demands from law enforcement and government authorities and regulators),or as required by applicable laws as amended from time to time.`,
                },
                {
                  name: `In order to investigate, prevent, or take action regarding suspected or actual prohibited activities, including but not limited to, fraud, illegal transactions and situations involving potential threats to the physical safety of any person or to prevent financial loss to any person or entity, including Us, Our customers, clients, and other related parties.`,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      desc: [
        {
          text: ` Questions, comments, and requests regarding this Policy are welcome and should be addressed to Our Grievance Officer, available at privacy@optifii.com\nWe pride ourselves on excellent customer service, but if You would like to make a complaint about the way in which We have collected or used Your Personal Information, please contact Us at privacy@optifii.com`,
          boldtext: [`Grievance officer`],
          links: [
            {
              name: "privacy@optifii.com",
              url: "mailto:privacy@optifii.com",
            },
          ],
        },
      ],
    },
  ],
};
